# Project WARLOCK - HUD Configuration
# Define which plugins to load and their settings

plugins:
  - name: BorderPaddingPlugin
    enabled: true
    visible: false  # Hidden by default, toggle with 'b' key
    z_index: 2  # Render early, but after background elements
    settings:
      padding_top: 40  # Pixels from top edge
      padding_bottom: 40  # Pixels from bottom edge
      padding_left: 40  # Pixels from left edge
      padding_right: 40  # Pixels from right edge
      padding_step: 5  # Adjustment step for [ and ] keys
      show_boundaries: true  # Show visual boundary lines
      boundary_color: [0, 255, 255]  # Yellow (BGR)
      boundary_thickness: 2
      show_measurements: true  # Show padding measurements

  - name: CompassPlugin
    enabled: true
    visible: true
    z_index: 10

  - name: MiniMapPlugin
    enabled: true
    visible: true
    z_index: 5
    settings:
      zoom_level: 300  # Initial zoom radius in meters
      show_terrain: true  # Enable terrain overlay

  - name: YOLODetectionPlugin
    enabled: true
    visible: true  # Visible by default, toggle with 'y' key
    z_index: 15  # Render after motion tracker but before FPS
    settings:
      model_path: yolo11n.pt
      confidence_threshold: 0.25
      friend_color: [255, 200, 100]  # Cyan blue (BGR)
      foe_color: [0, 100, 255]  # Orange/red (BGR)

  - name: FPSCounterPlugin
    enabled: true
    visible: false  # Hidden by default, toggle with 'f' key
    z_index: 100  # Render on top

  - name: PluginControlPanel
    enabled: true
    visible: false  # Hidden by default, toggle with 'p' key
    z_index: 1000  # Render on top of everything
