keybinds:
  system:
    quit: q
    help: h
    keybinds_panel: k
    save_frame: c
    plugin_panel: p

  yolo:
    toggle: y
    cycle_mode: v

  exposure:
    toggle: e
    toggle_stats: o
    brightness_up: "+"
    brightness_down: "-"

  display:
    toggle_fps: f
    toggle_borders: b
    padding_increase: "]"
    padding_decrease: "["
    toggle_map: m

  movement:
    forward: w
    backward: s
    left: a
    right: d

plugins:
  - name: AutoExposurePlugin
    enabled: true
    visible: true
    z_index: 1
    settings:
      target_brightness: 128
      brightness_tolerance: 15
      adjustment_speed: 0.15
      min_exposure: -13
      max_exposure: 0
      min_gain: 0
      max_gain: 100
      use_histogram_eq: false
      use_clahe: true
      enable_auto_gain: true
      enable_auto_exposure: true

  - name: BorderPaddingPlugin
    enabled: true
    visible: false
    z_index: 2
    settings:
      padding_top: 40
      padding_bottom: 40
      padding_left: 40
      padding_right: 40
      padding_step: 5
      show_boundaries: true
      boundary_color: [0, 255, 255]
      boundary_thickness: 2
      show_measurements: true

  - name: CompassPlugin
    enabled: true
    visible: true
    z_index: 10

  - name: MiniMapPlugin
    enabled: true
    visible: true
    z_index: 5
    settings:
      zoom_level: 300
      show_terrain: true

  - name: YOLODetectionPlugin
    enabled: true
    visible: true
    z_index: 15
    settings:
      model_path: yolo11n-seg.pt
      confidence_threshold: 0.25
      friend_color: [255, 200, 100]
      foe_color: [0, 100, 255]
      show_segmentation: true
      show_boxes: false

  - name: FPSCounterPlugin
    enabled: true
    visible: false
    z_index: 100

  - name: PluginControlPanel
    enabled: true
    visible: false
    z_index: 1000
